-- Paste this into your Supabase SQL Editor

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('bakso-sapi-premium', 'Kelas Bakso Sapi Premium', 'Belajar langsung dari ahlinya! Dengan pengalaman mengelola pabrik bakso sejak 1998, saya akan membongkar tuntas rahasia dapur membuat bakso sapi premium. Anda akan belajar teknik rahasia menghasilkan bakso yang kenyal, garing saat digigit, dan kaya rasa daging—kualitas standar industri yang kini bisa Anda ciptakan dari dapur rumah sendiri.', 'Rp 199.000', 3450, '60 Menit', 8, 'https://i.postimg.cc/t10xCGvR/image.png', 'https://jumpshare.com/embed/Lp5SdX6V3xnytDhsOW2j', ARRAY['Teknik memilih daging sapi yang tepat', 'Rahasia tekstur kenyal dan garing', 'Resep kuah kaldu bakso gurih', 'Tips penyimpanan agar awet'], true);

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('lapis-legit', 'Kelas Lapis Legit 3 Generasi', 'Kuasai resep warisan keluarga yang telah turun-temurun selama 3 generasi. Pelajari teknik memanggang selapis demi selapis untuk menghasilkan Lapis Legit yang moist, harum butter, dan bermotif cantik sempurna tanpa gagal.', 'Rp 399.000', 1250, '45 Menit', 5, 'https://i.postimg.cc/rmKx8jyp/LAPISLEGITPHOTO.png', '', ARRAY['Resep otentik warisan 3 generasi', 'Teknik memanggang lapis per lapis', 'Cara agar lapis legit moist & harum', 'Tips anti gagal untuk pemula'], false);INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('meat-pie', 'Kelas Meat Pie', 'Hadirkan sajian ala restoran bintang lima di rumah Anda. Pelajari teknik membuat kulit pie yang super renyah dan flaky, berpadu sempurna dengan isian daging sapi gurih yang meleleh di mulut berkat siraman saus demi-glace yang kaya rasa.', 'Rp 299.000', 890, '38 Menit', 6, 'https://i.postimg.cc/ppmR9mmT/MEATPIEPHOTO.png', '', ARRAY['Teknik membuat kulit pie shortcrust yang renyah, flaky, dan tidak remuk saat dipegang', 'Cara memasak isian daging sapi agar juicy, tidak alot, dan rasanya meresap sempurna', 'Teknik membuat saus demi-glace rumahan tanpa peralatan profesional — hasilnya seperti restoran', 'Cara merakit dan menutup pie agar tidak bocor dan bentuknya rapi saat dipanggang', 'Teknik memanggang dengan suhu dan waktu yang tepat agar hasilnya golden brown sempurna'], false);

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('ogura-softcake', 'Kelas Ogura Softcake (3 Varian)', 'Kuasai teknik membuat Ogura Softcake yang teksturnya seringan kapas dan lumer di mulut. Anda akan belajar langsung 3 varian rasa premium sekaligus: Matcha otentik, Cokelat pekat yang kaya rasa, dan Durian yang harum menggoda.', 'Rp 299.000', 1100, '25 Menit', 4, 'https://i.postimg.cc/YGnF2vsP/Chat-GPT-Image-Mar-17-2026-12-23-11-PM.png', '', ARRAY['Teknik dasar membuat adonan ogura agar teksturnya ringan seperti kapas dan lumer di mulut', 'Cara menggabungkan rasa matcha, cokelat, dan durian ke dalam adonan tanpa merusak tekstur', 'Rahasia memanggang ogura agar bagian atas tidak retak dan bagian tengah tidak bantat', 'Cara mengukur bahan dengan tepat untuk ketiga varian agar hasilnya konsisten setiap kali', 'Teknik mengeluarkan ogura dari loyang tanpa rusak untuk tampilan yang cantik dan rapi'], false);

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('mocha-pandan-sponge', 'Kelas Mocha & Pandan Sponge Cake', 'Bernostalgia dengan kelezatan kue klasik favorit keluarga. Pelajari teknik memanggang sponge cake yang super lembut, anti-bantat, dan mengembang sempurna, dipadukan dengan wangi harum pandan asli dan aroma mocha yang khas.', 'Rp 249.000', 950, '53 Menit', 5, 'https://i.postimg.cc/xqWkVnwy/Chat-GPT-Image-Mar-17-2026-04-54-28-PM.png', '', ARRAY['Teknik mengocok telur dan gula hingga ribbon stage — rahasia sponge yang mengembang sempurna', 'Cara melipat tepung ke dalam adonan agar kue tidak turun (deflate) dan tetap fluffy', 'Rahasia mendapatkan warna dan aroma pandan asli yang kuat, natural, dan tidak artifisial', 'Teknik memanggang sponge anti-bantat menggunakan oven rumahan biasa tanpa oven profesional', 'Cara memadukan layer mocha dan pandan agar kedua rasa seimbang dan tidak saling mendominasi'], false);

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('otak-otak', 'Kelas Otak-Otak', 'Bikin camilan gurih favorit semua orang! Pelajari cara mengolah ikan tenggiri menjadi otak-otak yang teksturnya kenyal pas, gurih meresap, dan memiliki aroma bakaran daun pisang yang sangat menggugah selera.', 'Rp 199.000', 1500, '17 Menit', 3, 'https://i.postimg.cc/tnCGLZ9S/Chat-GPT-Image-Mar-17-2026-04-58-17-PM.png', '', ARRAY['Cara memilih ikan tenggiri segar', 'Teknik menguleni adonan kenyal', 'Resep bumbu gurih meresap', 'Teknik membakar dengan daun pisang'], false);

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('go-hiong-roll', 'Kelas Go Hiong Roll (Rolade Daging)', 'Sajikan hidangan istimewa dengan mudah. Pelajari rahasia menggulung Go Hiong Roll yang kulitnya renyah krispi namun daging di dalamnya tetap juicy. Lengkap dengan takaran racikan bumbu ngohiong otentik yang wangi.', 'Rp 199.000', 1340, '18 Menit', 4, 'https://i.postimg.cc/RqSGMfNP/Chat-GPT-Image-Mar-17-2026-12-17-47-PM.png', '', ARRAY['Teknik meracik bumbu ngohiong otentik dengan takaran pas — tidak terlalu kuat, tidak kurang', 'Cara menguleni dan mencampur daging agar isian tetap juicy and tidak kering setelah dimasak', 'Teknik menggulung rolade agar rapat, tidak mudah lepas, dan bentuk tetap cantik saat dipotong', 'Cara menggoreng go hiong agar kulitnya krispi merata tanpa terlalu berminyak', 'Tips menyimpan dan memanaskan kembali go hiong agar kulitnya tetap renyah'], false);

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('fu-kian', 'Kelas Fu Kian', 'Kuasai teknik membuat Fu Kian (bakso ikan bungkus kulit tahu) ala restoran dimsum. Teksturnya dijamin gurih, kenyal, dan berpadu nikmat dengan kulit tahu. Sangat cocok untuk stok lauk keluarga maupun ide jualan yang laris manis.', 'Rp 199.000', 1800, '30 Menit', 4, 'https://i.postimg.cc/bGw4DMvm/Chat-GPT-Image-Mar-17-2026-12-14-11-PM.png', '', ARRAY['Cara membuat adonan bakso ikan yang kenyal, padat, dan bebas bau amis', 'Teknik membungkus isian dengan kulit tahu agar tidak robek saat dikukus maupun digoreng', 'Cara memilih dan menyiapkan kulit tahu berkualitas yang menghasilkan tekstur terbaik', 'Teknik memasak fu kian — kukus dan goreng — agar tekstur kenyal sempurna dan tidak keras', 'Tips mengemas fu kian sebagai produk frozen untuk dijual dari rumah dengan harga yang menguntungkan'], false);

