-- Paste this into your Supabase SQL Editor

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('bakso-sapi-premium', 'Kelas Bakso Sapi Premium', 'Belajar langsung dari ahlinya! Dengan pengalaman mengelola pabrik bakso sejak 1998, saya akan membongkar tuntas rahasia dapur membuat bakso sapi premium. Anda akan belajar teknik rahasia menghasilkan bakso yang kenyal, garing saat digigit, dan kaya rasa daging—kualitas standar industri yang kini bisa Anda ciptakan dari dapur rumah sendiri.', 'Rp 199.000', 3450, '60 Menit', 8, 'https://i.postimg.cc/t10xCGvR/image.png', 'https://jumpshare.com/embed/Lp5SdX6V3xnytDhsOW2j', ARRAY['Teknik memilih daging sapi yang tepat', 'Rahasia tekstur kenyal dan garing', 'Resep kuah kaldu bakso gurih', 'Tips penyimpanan agar awet'], true);

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('lapis-legit', 'Kelas Lapis Legit 3 Generasi', 'Kuasai resep warisan keluarga yang telah turun-temurun selama 3 generasi. Pelajari teknik memanggang selapis demi selapis untuk menghasilkan Lapis Legit yang moist, harum butter, dan bermotif cantik sempurna tanpa gagal.', 'Rp 399.000', 1250, '45 Menit', 5, 'https://i.postimg.cc/rmKx8jyp/LAPISLEGITPHOTO.png', '', ARRAY['Resep otentik warisan 3 generasi', 'Teknik memanggang lapis per lapis', 'Cara agar lapis legit moist & harum', 'Tips anti gagal untuk pemula'], false);

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('meat-pie', 'Kelas Meat Pie', 'Hadirkan sajian ala restoran bintang lima di rumah Anda. Pelajari teknik membuat kulit pie yang super renyah dan flaky, berpadu sempurna dengan isian daging sapi gurih yang meleleh di mulut berkat siraman saus demi-glace yang kaya rasa.', 'Rp 299.000', 890, '38 Menit', 6, 'https://i.postimg.cc/ppmR9mmT/MEATPIEPHOTO.png', '', ARRAY['Teknik kulit pie renyah & flaky', 'Resep isian daging sapi gurih', 'Cara membuat saus demi-glace', 'Tips memanggang pie sempurna'], false);

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('ogura-softcake', 'Kelas Ogura Softcake (3 Varian)', 'Kuasai teknik membuat Ogura Softcake yang teksturnya seringan kapas dan lumer di mulut. Anda akan belajar langsung 3 varian rasa premium sekaligus: Matcha otentik, Cokelat pekat yang kaya rasa, dan Durian yang harum menggoda.', 'Rp 299.000', 1100, '25 Menit', 4, 'https://i.postimg.cc/YGnF2vsP/Chat-GPT-Image-Mar-17-2026-12-23-11-PM.png', '', ARRAY['Teknik adonan selembut kapas', 'Resep varian Matcha otentik', 'Resep varian Cokelat pekat', 'Resep varian Durian harum'], false);

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('mocha-pandan-sponge', 'Kelas Mocha & Pandan Sponge Cake', 'Bernostalgia dengan kelezatan kue klasik favorit keluarga. Pelajari teknik memanggang sponge cake yang super lembut, anti-bantat, dan mengembang sempurna, dipadukan dengan wangi harum pandan asli dan aroma mocha yang khas.', 'Rp 249.000', 950, '53 Menit', 5, 'https://i.postimg.cc/xqWkVnwy/Chat-GPT-Image-Mar-17-2026-04-54-28-PM.png', '', ARRAY['Teknik sponge cake anti-bantat', 'Cara membuat pasta pandan asli', 'Resep varian aroma mocha klasik', 'Suhu oven yang tepat untuk sponge'], false);

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('otak-otak', 'Kelas Otak-Otak', 'Bikin camilan gurih favorit semua orang! Pelajari cara mengolah ikan tenggiri menjadi otak-otak yang teksturnya kenyal pas, gurih meresap, dan memiliki aroma bakaran daun pisang yang sangat menggugah selera.', 'Rp 199.000', 1500, '17 Menit', 3, 'https://i.postimg.cc/tnCGLZ9S/Chat-GPT-Image-Mar-17-2026-04-58-17-PM.png', '', ARRAY['Cara memilih ikan tenggiri segar', 'Teknik menguleni adonan kenyal', 'Resep bumbu gurih meresap', 'Teknik membakar dengan daun pisang'], false);

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('go-hiong-roll', 'Kelas Go Hiong Roll (Rolade Daging)', 'Sajikan hidangan istimewa dengan mudah. Pelajari rahasia menggulung Go Hiong Roll yang kulitnya renyah krispi namun daging di dalamnya tetap juicy. Lengkap dengan takaran racikan bumbu ngohiong otentik yang wangi.', 'Rp 199.000', 1340, '18 Menit', 4, 'https://i.postimg.cc/RqSGMfNP/Chat-GPT-Image-Mar-17-2026-12-17-47-PM.png', '', ARRAY['Resep racikan bumbu ngohiong', 'Teknik menggulung kulit renyah', 'Cara agar daging tetap juicy', 'Tips menggoreng krispi sempurna'], false);

INSERT INTO courses (slug, title, description, price, students, duration, modules, image, video, benefits, isSignature)
VALUES ('fu-kian', 'Kelas Fu Kian', 'Kuasai teknik membuat Fu Kian (bakso ikan bungkus kulit tahu) ala restoran dimsum. Teksturnya dijamin gurih, kenyal, dan berpadu nikmat dengan kulit tahu. Sangat cocok untuk stok lauk keluarga maupun ide jualan yang laris manis.', 'Rp 199.000', 1800, '30 Menit', 4, 'https://i.postimg.cc/bGw4DMvm/Chat-GPT-Image-Mar-17-2026-12-14-11-PM.png', '', ARRAY['Teknik adonan bakso ikan kenyal', 'Cara membungkus dengan kulit tahu', 'Resep kuah kaldu pendamping', 'Tips penyimpanan untuk ide jualan'], false);

