// AUTO-GENERATED by scripts/sync-fallback-catalog.ts — do not edit by hand.
// This is the offline fallback the site renders when Supabase is
// unreachable. Editing it by hand reintroduces catalog drift; run
// `npx tsx scripts/sync-fallback-catalog.ts` instead.
export const courses = [
  {
    id: "0d333428-052f-4f3a-ab96-1fbc146b3cb1",
    slug: "bakso-sapi-premium",
    isSignature: true,
    title: "Kelas Bakso Sapi Premium",
    description: "<p><strong>Belajar</strong> langsung dari ahlinya! Dengan pengalaman mengelola pabrik bakso sejak 1998, saya akan membongkar tuntas rahasia dapur membuat bakso sapi premium. Anda akan belajar teknik rahasia menghasilkan bakso yang kenyal, garing saat digigit, dan kaya rasa daging—kualitas standar industri yang kini bisa Anda ciptakan dari dapur rumah sendiri.</p>",
    price: "Rp 399.000",
    students: 4509,
    duration: "40 menit",
    modules: 0,
    imageUrl: "/images/bakso-sapi-premium.webp",
    benefits: [
      "Teknik menggiling dan menguleni daging sapi agar tekstur bakso kenyal   sempurna tanpa alat pabrik",
      "Cara membuat bumbu rahasia yang membuat bakso kaya rasa daging asli,   bukan rasa tepung",
      "Rahasia mencampur tepung dengan takaran pas agar bakso garing saat   digigit dan tidak melempem",
      "Teknik merebus bakso agar tidak pecah, bentuk tetap bulat sempurna, dan warna menggiurkan",
      "Cara menghitung takaran bahan untuk hasil yang konsisten setiap kali   memasak"
    ]
  },
  {
    id: "6f1f36b8-a34d-455d-98c7-ed7c80af1833",
    slug: "fu-kian",
    isSignature: false,
    title: "Kelas Fu Kian",
    description: "Kuasai teknik membuat Fu Kian (bakso ikan bungkus kulit tahu) ala restoran dimsum. Teksturnya dijamin gurih, kenyal, dan berpadu nikmat dengan kulit tahu. Sangat cocok untuk stok lauk keluarga maupun ide jualan yang laris manis.",
    price: "Rp 199.000",
    students: 71,
    duration: "28 menit",
    modules: 0,
    imageUrl: "/images/fu-kian.webp",
    benefits: [
      "Cara membuat adonan bakso ikan yang kenyal, padat, dan bebas bau amis",
      "Teknik membungkus isian dengan kulit tahu agar tidak robek saat dikukus maupun digoreng",
      "Cara memilih dan menyiapkan kulit tahu berkualitas yang menghasilkan tekstur terbaik",
      "Teknik memasak fu kian — kukus dan goreng — agar tekstur kenyal sempurna dan tidak keras",
      "Tips mengemas fu kian sebagai produk frozen untuk dijual dari rumah dengan harga yang menguntungkan"
    ]
  },
  {
    id: "93352de0-4e79-446e-a937-884c3919769c",
    slug: "go-hiong-roll",
    isSignature: false,
    title: "Kelas Go Hiong Roll (Rolade Daging)",
    description: "Sajikan hidangan istimewa dengan mudah. Pelajari rahasia menggulung Go Hiong Roll yang kulitnya renyah krispi namun daging di dalamnya tetap juicy. Lengkap dengan takaran racikan bumbu ngohiong otentik yang wangi.",
    price: "Rp 199.000",
    students: 270,
    duration: "21 menit",
    modules: 0,
    imageUrl: "/images/go-hiong-roll.webp",
    benefits: [
      "Teknik meracik bumbu ngohiong otentik dengan takaran pas — tidak terlalu kuat, tidak kurang",
      "Cara menguleni dan mencampur daging agar isian tetap juicy dan tidak kering setelah dimasak",
      "Teknik menggulung rolade agar rapat, tidak mudah lepas, dan bentuk tetap cantik saat dipotong",
      "Cara menggoreng go hiong agar kulitnya krispi merata tanpa terlalu berminyak",
      "Tips menyimpan dan memanaskan kembali go hiong agar kulitnya tetap renyah"
    ]
  },
  {
    id: "8ce31491-0437-451f-ac08-31f4288ebbdf",
    slug: "lapis-legit",
    isSignature: false,
    title: "Kelas Lapis Legit 3 Generasi",
    description: "Kuasai resep warisan keluarga yang telah turun-temurun selama 3 generasi. Pelajari teknik memanggang selapis demi selapis untuk menghasilkan Lapis Legit yang moist, harum butter, dan bermotif cantik sempurna tanpa gagal.",
    price: "Rp 599.000",
    students: 1100,
    duration: "62 menit",
    modules: 0,
    imageUrl: "/images/lapis-legit.webp",
    benefits: [
      "Teknik mengocok mentega dan telur hingga konsistensi adonan yang tepat —    kunci utama lapisan tidak bantat",
      "Cara mengatur suhu oven dan posisi loyang agar setiap lapisan matang merata tanpa gosong",
      "Rahasia mendapatkan motif lapis yang cantik, rapi, dan foto-worthy di setiap irisan",
      "Teknik memanggang selapis demi selapis dengan timing yang presisi agar tekstur lembut dan moist"
    ]
  },
  {
    id: "4a4bb9f9-bb45-48da-b53c-83bc5de72f44",
    slug: "meat-pie",
    isSignature: false,
    title: "Kelas Meat Pie",
    description: "Hadirkan sajian ala restoran bintang lima di rumah Anda. Pelajari teknik membuat kulit pie yang super renyah dan flaky, berpadu sempurna dengan isian daging sapi gurih yang meleleh di mulut berkat siraman saus demi-glace yang kaya rasa.",
    price: "Rp 399.000",
    students: 561,
    duration: "40 menit",
    modules: 0,
    imageUrl: "/images/meat-pie.webp",
    benefits: [
      "Teknik membuat kulit pie shortcrust yang renyah, flaky, dan tidak remuk saat dipegang",
      "Cara memasak isian daging sapi agar juicy, tidak alot, dan rasanya meresap sempurna",
      "Teknik membuat saus demi-glace rumahan tanpa peralatan profesional — hasilnya seperti restoran",
      "Cara merakit dan menutup pie agar tidak bocor dan bentuknya rapi saat dipanggang",
      "Teknik memanggang dengan suhu dan waktu yang tepat agar hasilnya golden brown sempurna"
    ]
  },
  {
    id: "c0d0cfd8-deae-4110-8778-d2a9f398de01",
    slug: "mocha-pandan-sponge",
    isSignature: false,
    title: "Kelas Mocha & Pandan Sponge Cake",
    description: "Bernostalgia dengan kelezatan kue klasik favorit keluarga. Pelajari teknik memanggang sponge cake yang super lembut, anti-bantat, dan mengembang sempurna, dipadukan dengan wangi harum pandan asli dan aroma mocha yang khas.",
    price: "Rp 249.000",
    students: 1255,
    duration: "37 menit",
    modules: 0,
    imageUrl: "/images/mocha-pandan-sponge.webp",
    benefits: [
      "Teknik mengocok telur dan gula hingga ribbon stage — rahasia sponge yang mengembang sempurna",
      "Cara melipat tepung ke dalam adonan agar kue tidak turun (deflate) dan tetap fluffy",
      "Rahasia mendapatkan warna dan aroma pandan asli yang kuat, natural, dan tidak artifisial",
      "Teknik memanggang sponge anti-bantat menggunakan oven rumahan biasa tanpa oven profesional",
      "Cara memadukan layer mocha dan pandan agar kedua rasa seimbang dan tidak saling mendominasi"
    ]
  },
  {
    id: "ca6db32a-a837-4842-b7d3-a1a37af2cfdd",
    slug: "ogura-softcake",
    isSignature: false,
    title: "Kelas Ogura Softcake (3 Varian)",
    description: "Kuasai teknik membuat Ogura Softcake yang teksturnya seringan kapas dan lumer di mulut. Anda akan belajar langsung 3 varian rasa premium sekaligus: Matcha otentik, Cokelat pekat yang kaya rasa, dan Durian yang harum menggoda.",
    price: "Rp 299.000",
    students: 725,
    duration: "33 menit",
    modules: 0,
    imageUrl: "/images/ogura-softcake.webp",
    benefits: [
      "Teknik dasar membuat adonan ogura agar teksturnya ringan seperti kapas dan lumer di mulut",
      "Cara menggabungkan rasa matcha, cokelat, dan durian ke dalam adonan tanpa merusak tekstur",
      "Rahasia memanggang ogura agar bagian atas tidak retak dan bagian tengah tidak bantat",
      "Cara mengukur bahan dengan tepat untuk ketiga varian agar hasilnya konsisten setiap kali",
      "Teknik mengeluarkan ogura dari loyang tanpa rusak untuk tampilan yang cantik dan rapi"
    ]
  },
  {
    id: "325a4e00-cf48-45e4-8550-a862654fed32",
    slug: "otak-otak",
    isSignature: false,
    title: "Kelas Otak-Otak",
    description: "Bikin camilan gurih favorit semua orang! Pelajari cara mengolah ikan tenggiri menjadi otak-otak yang teksturnya kenyal pas, gurih meresap, dan memiliki aroma bakaran daun pisang yang sangat menggugah selera.",
    price: "Rp 299.000",
    students: 1533,
    duration: "26 menit",
    modules: 0,
    imageUrl: "/images/otak-otak.webp",
    benefits: [
      "Cara memilih dan mengolah ikan tenggiri segar agar otak-otak tidak amis   sama sekali",
      " Teknik mencampur bumbu agar rasa gurih meresap sempurna ke seluruh   adonan ikan",
      "Tips membuat dalam jumlah besar untuk stok frozen atau dijual dari rumah"
    ]
  }
];
