// Regenerates the static fallback catalogs in app/data/ from Supabase.
//
// Every catalog read path (app/kursus, app/toko, app/page.tsx,
// components/ProductDetail, lib/search, lib/chatbot-knowledge, app/sitemap)
// silently substitutes these files whenever a Supabase query errors, times
// out, or returns zero rows. That means any drift between Supabase and these
// files shows up on the live site as a second, stale version of the catalog —
// e.g. a course priced Rp 299.000 in Supabase rendering as Rp 199.000 for
// whichever requests hit the fallback path.
//
// Run this after every catalog edit in /admin so the fallback stays a byte-
// for-byte mirror of the live data:
//
//   npx tsx scripts/sync-fallback-catalog.ts          # rewrite the files
//   npx tsx scripts/sync-fallback-catalog.ts --check  # CI: fail on drift
//
// Pass --localize-images to also download each course photo into
// public/images/<slug>.webp and point the fallback at the checked-in copy
// instead of a remote URL, so the images survive both a dead image host and a
// restricted Supabase project. Requires storage egress, so it cannot run while
// the project is returning 402.
//
// Uses the service-role key (server-side only, bypasses RLS) so it must be
// run locally and never shipped to the client.
import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

config({ path: '.env.local' });

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!url || !serviceKey) {
  throw new Error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local');
}

const supabase = createClient(url, serviceKey);
const checkOnly = process.argv.includes('--check');
const localizeImages = process.argv.includes('--localize-images');

// --only=courses / --only=products limits the run to one catalog. Needed
// because the two are not equally safe to regenerate: many `items` rows still
// carry remote Supabase storage URLs, so rewriting products.ts wholesale would
// undo 8520dd9, which deliberately moved the shop onto checked-in local images.
const onlyArg = process.argv.find((arg) => arg.startsWith('--only='));
const only = onlyArg ? onlyArg.slice('--only='.length) : null;

if (only && only !== 'courses' && only !== 'products') {
  throw new Error(`--only must be "courses" or "products", got "${only}"`);
}

const IMAGE_DIR = path.join(process.cwd(), 'public/images');

const COURSES_FILE = path.join(process.cwd(), 'app/data/courses.ts');
const PRODUCTS_FILE = path.join(process.cwd(), 'app/data/products.ts');

// Column order used when serializing, so regenerated files stay diff-stable
// instead of reshuffling on every run.
const COURSE_KEYS = [
  'id',
  'slug',
  'isSignature',
  'title',
  'description',
  'price',
  'originalPrice',
  'students',
  'duration',
  'modules',
  'imageUrl',
  'video',
  'benefits',
] as const;

const PRODUCT_KEYS = [
  'id',
  'name',
  'description',
  'price',
  'category',
  'imageUrl',
  'createdAt',
] as const;

function serialize(value: unknown, indent: string): string {
  if (value === null || value === undefined) return 'undefined';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const inner = value
      .map((entry) => `${indent}  ${serialize(entry, `${indent}  `)}`)
      .join(',\n');
    return `[\n${inner}\n${indent}]`;
  }
  return JSON.stringify(value);
}

function renderRows(rows: Record<string, unknown>[], keys: readonly string[]): string {
  return rows
    .map((row) => {
      const fields = keys
        .filter((key) => row[key] !== null && row[key] !== undefined)
        .map((key) => `    ${key}: ${serialize(row[key], '    ')}`)
        .join(',\n');
      return `  {\n${fields}\n  }`;
    })
    .join(',\n');
}

function renderFile(
  exportName: string,
  rows: Record<string, unknown>[],
  keys: readonly string[],
): string {
  return [
    '// AUTO-GENERATED by scripts/sync-fallback-catalog.ts — do not edit by hand.',
    '// This is the offline fallback the site renders when Supabase is',
    '// unreachable. Editing it by hand reintroduces catalog drift; run',
    '// `npx tsx scripts/sync-fallback-catalog.ts` instead.',
    `export const ${exportName} = [`,
    renderRows(rows, keys),
    '];',
    '',
  ].join('\n');
}

// The `items` table stores the shop catalog; app/data/products.ts exports it
// as `products`, so map the shapes rather than assuming they match.
function normalizeProduct(row: Record<string, unknown>): Record<string, unknown> {
  return {
    id: row.id,
    name: row.name,
    description: row.description,
    price: row.price,
    category: row.category,
    imageUrl: row.imageUrl ?? row.imageurl ?? row.image_url,
    createdAt: row.createdAt ?? row.createdat ?? row.created_at,
  };
}

function normalizeCourse(row: Record<string, unknown>): Record<string, unknown> {
  return {
    ...row,
    originalPrice: row.originalPrice ?? row.originalprice ?? row.original_price,
    imageUrl: row.imageUrl ?? row.imageurl ?? row.image_url,
    isSignature: row.isSignature ?? row.issignature ?? row.is_signature,
  };
}

// Downloads a course image and re-encodes it into public/images/<slug>.webp at
// its native resolution, returning the local path to store in the fallback.
//
// Without this the fallback points at whatever host the catalog happens to use,
// which is how the course photos rotted: four of them hotlinked i.postimg.cc,
// that host went away, and Next's image optimizer cached the 180x120 stub it
// got back. A checked-in file cannot rot, and cannot 402 when Supabase is
// restricted. Native resolution is deliberate — an earlier pass capped these at
// 1000px and the cards visibly softened on retina screens.
async function localizeImage(slug: string, remoteUrl: string): Promise<string> {
  const localPath = `/images/${slug}.webp`;
  const destination = path.join(IMAGE_DIR, `${slug}.webp`);

  if (!/^https?:\/\//.test(remoteUrl)) {
    return remoteUrl;
  }

  const response = await fetch(remoteUrl);
  if (!response.ok) {
    throw new Error(
      `Failed to download image for "${slug}" (${response.status}): ${remoteUrl}`,
    );
  }

  const input = Buffer.from(await response.arrayBuffer());
  const { width, height } = await sharp(input).metadata();
  const output = await sharp(input).webp({ quality: 82, effort: 6 }).toBuffer();

  fs.mkdirSync(IMAGE_DIR, { recursive: true });
  fs.writeFileSync(destination, output);
  console.log(
    `  ${slug}: ${width}x${height}  ${(input.length / 1024).toFixed(0)}KB -> ${(output.length / 1024).toFixed(0)}KB`,
  );

  return localPath;
}

async function fetchTable(table: string) {
  const { data, error } = await supabase.from(table).select('*');
  if (error) {
    throw new Error(`Failed to read "${table}" from Supabase: ${error.message}`);
  }
  if (!data || data.length === 0) {
    // Writing an empty fallback would make every failed query render an empty
    // catalog, which is worse than the stale data it replaces.
    throw new Error(`Refusing to sync: "${table}" returned zero rows.`);
  }
  return data as Record<string, unknown>[];
}

async function main() {
  const doCourses = only !== 'products';
  const doProducts = only !== 'courses';

  const courseRows = doCourses
    ? (await fetchTable('courses'))
        .map(normalizeCourse)
        .sort((a, b) => String(a.slug).localeCompare(String(b.slug)))
    : [];
  const productRows = doProducts
    ? (await fetchTable('items'))
        .map(normalizeProduct)
        .sort((a, b) => String(a.name).localeCompare(String(b.name)))
    : [];

  if (localizeImages && doCourses) {
    console.log('Localizing course images:');
    for (const row of courseRows) {
      if (typeof row.imageUrl === 'string' && row.imageUrl) {
        row.imageUrl = await localizeImage(String(row.slug), row.imageUrl);
      }
    }
  }

  const targets = [
    ...(doCourses
      ? [{ file: COURSES_FILE, next: renderFile('courses', courseRows, COURSE_KEYS), label: 'courses' }]
      : []),
    ...(doProducts
      ? [{ file: PRODUCTS_FILE, next: renderFile('products', productRows, PRODUCT_KEYS), label: 'products' }]
      : []),
  ];

  let drifted = false;

  for (const { file, next, label } of targets) {
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (current === next) {
      console.log(`${label}: up to date (${label === 'courses' ? courseRows.length : productRows.length} rows)`);
      continue;
    }
    drifted = true;
    if (checkOnly) {
      console.error(`${label}: DRIFT — app/data fallback does not match Supabase.`);
    } else {
      fs.writeFileSync(file, next);
      console.log(`${label}: rewrote ${path.relative(process.cwd(), file)}`);
    }
  }

  if (checkOnly && drifted) {
    console.error('\nRun `npx tsx scripts/sync-fallback-catalog.ts` to resync.');
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
