// Regenerates the static fallback catalogs in app/data/ from Supabase.
//
// Every catalog read path (app/kursus, app/toko, app/page.tsx,
// components/ProductDetail, lib/search, lib/chatbot-knowledge, app/sitemap)
// silently substitutes these files whenever a Supabase query errors, times
// out, or returns zero rows. That means any drift between Supabase and these
// files shows up on the live site as a second, stale version of the catalog —
// e.g. a course priced Rp 299.000 in Supabase rendering as Rp 199.000 for
// whichever requests hit the fallback path.
//
// Run this after every catalog edit in /admin so the fallback stays a byte-
// for-byte mirror of the live data:
//
//   npx tsx scripts/sync-fallback-catalog.ts          # rewrite the files
//   npx tsx scripts/sync-fallback-catalog.ts --check  # CI: fail on drift
//
// Uses the service-role key (server-side only, bypasses RLS) so it must be
// run locally and never shipped to the client.
import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';
import fs from 'node:fs';
import path from 'node:path';

config({ path: '.env.local' });

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!url || !serviceKey) {
  throw new Error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local');
}

const supabase = createClient(url, serviceKey);
const checkOnly = process.argv.includes('--check');

const COURSES_FILE = path.join(process.cwd(), 'app/data/courses.ts');
const PRODUCTS_FILE = path.join(process.cwd(), 'app/data/products.ts');

// Column order used when serializing, so regenerated files stay diff-stable
// instead of reshuffling on every run.
const COURSE_KEYS = [
  'id',
  'slug',
  'isSignature',
  'title',
  'description',
  'price',
  'originalPrice',
  'students',
  'duration',
  'modules',
  'imageUrl',
  'video',
  'benefits',
] as const;

const PRODUCT_KEYS = [
  'id',
  'name',
  'description',
  'price',
  'category',
  'imageUrl',
  'createdAt',
] as const;

function serialize(value: unknown, indent: string): string {
  if (value === null || value === undefined) return 'undefined';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const inner = value
      .map((entry) => `${indent}  ${serialize(entry, `${indent}  `)}`)
      .join(',\n');
    return `[\n${inner}\n${indent}]`;
  }
  return JSON.stringify(value);
}

function renderRows(rows: Record<string, unknown>[], keys: readonly string[]): string {
  return rows
    .map((row) => {
      const fields = keys
        .filter((key) => row[key] !== null && row[key] !== undefined)
        .map((key) => `    ${key}: ${serialize(row[key], '    ')}`)
        .join(',\n');
      return `  {\n${fields}\n  }`;
    })
    .join(',\n');
}

function renderFile(
  exportName: string,
  rows: Record<string, unknown>[],
  keys: readonly string[],
): string {
  return [
    '// AUTO-GENERATED by scripts/sync-fallback-catalog.ts — do not edit by hand.',
    '// This is the offline fallback the site renders when Supabase is',
    '// unreachable. Editing it by hand reintroduces catalog drift; run',
    '// `npx tsx scripts/sync-fallback-catalog.ts` instead.',
    `export const ${exportName} = [`,
    renderRows(rows, keys),
    '];',
    '',
  ].join('\n');
}

// The `items` table stores the shop catalog; app/data/products.ts exports it
// as `products`, so map the shapes rather than assuming they match.
function normalizeProduct(row: Record<string, unknown>): Record<string, unknown> {
  return {
    id: row.id,
    name: row.name,
    description: row.description,
    price: row.price,
    category: row.category,
    imageUrl: row.imageUrl ?? row.imageurl ?? row.image_url,
    createdAt: row.createdAt ?? row.createdat ?? row.created_at,
  };
}

function normalizeCourse(row: Record<string, unknown>): Record<string, unknown> {
  return {
    ...row,
    originalPrice: row.originalPrice ?? row.originalprice ?? row.original_price,
    imageUrl: row.imageUrl ?? row.imageurl ?? row.image_url,
    isSignature: row.isSignature ?? row.issignature ?? row.is_signature,
  };
}

async function fetchTable(table: string) {
  const { data, error } = await supabase.from(table).select('*');
  if (error) {
    throw new Error(`Failed to read "${table}" from Supabase: ${error.message}`);
  }
  if (!data || data.length === 0) {
    // Writing an empty fallback would make every failed query render an empty
    // catalog, which is worse than the stale data it replaces.
    throw new Error(`Refusing to sync: "${table}" returned zero rows.`);
  }
  return data as Record<string, unknown>[];
}

async function main() {
  const courseRows = (await fetchTable('courses'))
    .map(normalizeCourse)
    .sort((a, b) => String(a.slug).localeCompare(String(b.slug)));
  const productRows = (await fetchTable('items'))
    .map(normalizeProduct)
    .sort((a, b) => String(a.name).localeCompare(String(b.name)));

  const targets = [
    { file: COURSES_FILE, next: renderFile('courses', courseRows, COURSE_KEYS), label: 'courses' },
    { file: PRODUCTS_FILE, next: renderFile('products', productRows, PRODUCT_KEYS), label: 'products' },
  ];

  let drifted = false;

  for (const { file, next, label } of targets) {
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (current === next) {
      console.log(`${label}: up to date (${label === 'courses' ? courseRows.length : productRows.length} rows)`);
      continue;
    }
    drifted = true;
    if (checkOnly) {
      console.error(`${label}: DRIFT — app/data fallback does not match Supabase.`);
    } else {
      fs.writeFileSync(file, next);
      console.log(`${label}: rewrote ${path.relative(process.cwd(), file)}`);
    }
  }

  if (checkOnly && drifted) {
    console.error('\nRun `npx tsx scripts/sync-fallback-catalog.ts` to resync.');
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
